/* DO NOT EDIT THIS FILE - it is machine generated */
#include "elroykanye_Jni.h"
/* Header for class elroykanye_Jni */

#ifndef _Included_elroykanye_Jni
#define _Included_elroykanye_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     elroykanye_Jni
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_elroykanye_Jni_print (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
